# Generated by Django 2.0.1 on 2018-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
