# Generated by Django 2.0.1 on 2018-02-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180221_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
