# Generated by Django 2.0.1 on 2018-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='character_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='story_type',
            field=models.CharField(max_length=254),
        ),
    ]
