# Generated by Django 2.0.1 on 2018-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20180222_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companion',
            field=models.CharField(default='images/female/Koko/talk1.png', max_length=254),
            preserve_default=False,
        ),
    ]
