# Generated by Django 2.0.1 on 2018-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_profile_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mood',
            field=models.IntegerField(default=0),
        ),
    ]
